version: "3"
services:
  postgres:
    container_name: eab_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  # pgadmin:
  #   links:
  #     - postgres:postgres
  #   container_name: eab_pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - /data/pgadmin:/root/.pgadmin
  #   env_file:
  #     - docker.env
  #   networks:
  #     - postgres

  minio:
    image: minio/minio
    container_name: eab_s3
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    env_file:
      - docker.env
    command: server --console-address ":9001" /data

networks:
  postgres:
    driver: bridge

volumes:
  minio_storage: {}
