import { NotificationsListResponseWithCount } from '@pages/notifications/types'

export const mock: NotificationsListResponseWithCount = {
    count: 11,
    list: [
        {
            id: 1,
            guid: 'd29d7c46-ad03-4c8c-a38f-1fdcd72402de',
            source: 'dictionaryservice',
            templateCode: null,
            params: '{"urn":"urn:test:countries","shortName":"Справочник стран","changes":[{"name":"description","oldValue":"Справочник стран7","newValue":"Справочник стран8"}],"addedAttrs":[],"deletedAttrs":[],"changedAttrs":[],"empty":false}',
            title: 'Admin Dictionary, обновлен справочник',
            content: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmail: null,
            contentPush: null,
            contentTelegram: null,
            contentSms: null,
            contentRocket: null,
            recipientId: null,
            creationDate: 1693247509814,
            readDate: null,
            contentSmsSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentPushSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentRocketSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmailSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentTelegramSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            status: 'new',
        },
        {
            id: 2,
            guid: 'd29d7c46-ad03-4c8c-a38f-1fdcd72402de',
            source: 'dictionaryservice',
            templateCode: null,
            params: '{"urn":"urn:test:countries","shortName":"Справочник стран","changes":[{"name":"description","oldValue":"Справочник стран7","newValue":"Справочник стран8"}],"addedAttrs":[],"deletedAttrs":[],"changedAttrs":[],"empty":false}',
            title: 'Admin Dictionary, обновлен справочник',
            content: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmail: null,
            contentPush: null,
            contentTelegram: null,
            contentSms: null,
            contentRocket: null,
            recipientId: null,
            creationDate: 1693247509814,
            readDate: 1693247509814,
            contentSmsSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentPushSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentRocketSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmailSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentTelegramSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            status: 'read',
        },
        {
            id: 3,
            guid: 'd29d7c46-ad03-4c8c-a38f-1fdcd72402de',
            source: 'dictionaryservice',
            templateCode: null,
            params: '{"urn":"urn:test:countries","shortName":"Справочник стран","changes":[{"name":"description","oldValue":"Справочник стран7","newValue":"Справочник стран8"}],"addedAttrs":[],"deletedAttrs":[],"changedAttrs":[],"empty":false}',
            title: 'Admin Dictionary, обновлен справочник',
            content: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmail: null,
            contentPush: null,
            contentTelegram: null,
            contentSms: null,
            contentRocket: null,
            recipientId: null,
            creationDate: 1693247509814,
            readDate: 1693247509814,
            contentSmsSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentPushSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentRocketSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmailSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentTelegramSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            status: 'read',
        },
        {
            id: 4,
            guid: 'd29d7c46-ad03-4c8c-a38f-1fdcd72402de',
            source: 'dictionaryservice',
            templateCode: null,
            params: '{"urn":"urn:test:countries","shortName":"Справочник стран","changes":[{"name":"description","oldValue":"Справочник стран7","newValue":"Справочник стран8"}],"addedAttrs":[],"deletedAttrs":[],"changedAttrs":[],"empty":false}',
            title: 'Admin Dictionary, обновлен справочник',
            content: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmail: null,
            contentPush: null,
            contentTelegram: null,
            contentSms: null,
            contentRocket: null,
            recipientId: null,
            creationDate: 1693247509814,
            readDate: 1693247509814,
            contentSmsSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentPushSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentRocketSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmailSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentTelegramSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            status: 'read',
        },
        {
            id: 5,
            guid: 'd29d7c46-ad03-4c8c-a38f-1fdcd72402de',
            source: 'dictionaryservice',
            templateCode: null,
            params: '{"urn":"urn:test:countries","shortName":"Справочник стран","changes":[{"name":"description","oldValue":"Справочник стран7","newValue":"Справочник стран8"}],"addedAttrs":[],"deletedAttrs":[],"changedAttrs":[],"empty":false}',
            title: 'Admin Dictionary, обновлен справочник',
            content: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmail: null,
            contentPush: null,
            contentTelegram: null,
            contentSms: null,
            contentRocket: null,
            recipientId: null,
            creationDate: 1693247509814,
            readDate: 1693247509814,
            contentSmsSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentPushSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentRocketSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmailSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentTelegramSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            status: 'read',
        },
        {
            id: 6,
            guid: 'd29d7c46-ad03-4c8c-a38f-1fdcd72402de',
            source: 'dictionaryservice',
            templateCode: null,
            params: '{"urn":"urn:test:countries","shortName":"Справочник стран","changes":[{"name":"description","oldValue":"Справочник стран7","newValue":"Справочник стран8"}],"addedAttrs":[],"deletedAttrs":[],"changedAttrs":[],"empty":false}',
            title: 'Admin Dictionary, обновлен справочник',
            content: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmail: null,
            contentPush: null,
            contentTelegram: null,
            contentSms: null,
            contentRocket: null,
            recipientId: null,
            creationDate: 1693247509814,
            readDate: 1693247509814,
            contentSmsSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentPushSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentRocketSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmailSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentTelegramSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            status: 'read',
        },
        {
            id: 7,
            guid: 'd29d7c46-ad03-4c8c-a38f-1fdcd72402de',
            source: 'dictionaryservice',
            templateCode: null,
            params: '{"urn":"urn:test:countries","shortName":"Справочник стран","changes":[{"name":"description","oldValue":"Справочник стран7","newValue":"Справочник стран8"}],"addedAttrs":[],"deletedAttrs":[],"changedAttrs":[],"empty":false}',
            title: 'Admin Dictionary, обновлен справочник',
            content: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmail: null,
            contentPush: null,
            contentTelegram: null,
            contentSms: null,
            contentRocket: null,
            recipientId: null,
            creationDate: 1693247509814,
            readDate: 1693247509814,
            contentSmsSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentPushSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentRocketSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmailSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentTelegramSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            status: 'read',
        },
        {
            id: 8,
            guid: 'd29d7c46-ad03-4c8c-a38f-1fdcd72402de',
            source: 'dictionaryservice',
            templateCode: null,
            params: '{"urn":"urn:test:countries","shortName":"Справочник стран","changes":[{"name":"description","oldValue":"Справочник стран7","newValue":"Справочник стран8"}],"addedAttrs":[],"deletedAttrs":[],"changedAttrs":[],"empty":false}',
            title: 'Admin Dictionary, обновлен справочник',
            content: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmail: null,
            contentPush: null,
            contentTelegram: null,
            contentSms: null,
            contentRocket: null,
            recipientId: null,
            creationDate: 1693247509814,
            readDate: 1693247509814,
            contentSmsSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentPushSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentRocketSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmailSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentTelegramSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            status: 'read',
        },
        {
            id: 9,
            guid: 'd29d7c46-ad03-4c8c-a38f-1fdcd72402de',
            source: 'dictionaryservice',
            templateCode: null,
            params: '{"urn":"urn:test:countries","shortName":"Справочник стран","changes":[{"name":"description","oldValue":"Справочник стран7","newValue":"Справочник стран8"}],"addedAttrs":[],"deletedAttrs":[],"changedAttrs":[],"empty":false}',
            title: 'Admin Dictionary, обновлен справочник',
            content: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmail: null,
            contentPush: null,
            contentTelegram: null,
            contentSms: null,
            contentRocket: null,
            recipientId: null,
            creationDate: 1693247509814,
            readDate: 1693247509814,
            contentSmsSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentPushSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentRocketSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmailSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentTelegramSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            status: 'read',
        },
        {
            id: 10,
            guid: 'd29d7c46-ad03-4c8c-a38f-1fdcd72402de',
            source: 'dictionaryservice',
            templateCode: null,
            params: '{"urn":"urn:test:countries","shortName":"Справочник стран","changes":[{"name":"description","oldValue":"Справочник стран7","newValue":"Справочник стран8"}],"addedAttrs":[],"deletedAttrs":[],"changedAttrs":[],"empty":false}',
            title: 'Admin Dictionary, обновлен справочник',
            content: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmail: null,
            contentPush: null,
            contentTelegram: null,
            contentSms: null,
            contentRocket: null,
            recipientId: null,
            creationDate: 1693247509814,
            readDate: 1693247509814,
            contentSmsSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentPushSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentRocketSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmailSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentTelegramSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            status: 'read',
        },
        {
            id: 11,
            guid: 'd29d7c46-ad03-4c8c-a38f-1fdcd72402de',
            source: 'dictionaryservice',
            templateCode: null,
            params: '{"urn":"urn:test:countries","shortName":"Справочник стран","changes":[{"name":"description","oldValue":"Справочник стран7","newValue":"Справочник стран8"}],"addedAttrs":[],"deletedAttrs":[],"changedAttrs":[],"empty":false}',
            title: 'Admin Dictionary, обновлен справочник',
            content: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmail: null,
            contentPush: null,
            contentTelegram: null,
            contentSms: null,
            contentRocket: null,
            recipientId: null,
            creationDate: 1693247509814,
            readDate: 1693247509814,
            contentSmsSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentPushSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentRocketSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentEmailSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            contentTelegramSafe: 'Обновлен справочник urn:test:countries (Справочник стран)',
            status: 'read',
        },
    ],
}
